### ISSUE TITLE
First Pass at guc-test assets to bring over

### ISSUE THREAD

**Issue by beersandrew** [usd-wg/assets#39]
# guc test Asset Review
All guc test assets can be found [here](https://github.com/pablode/guc-tests/tree/main/tests)

## Notes / Comments

1. guc-tests has a lot of tests that compare UsdPreviewShader and MaterialX, we already have MaterialXTest but not really a comparison, so maybe a comparison is useful
2. guc-tests includes some more full-asset tests as well, but this review was focused more on feature tests / unit tests

## Repo Comparison Table
|  guc-test assets                  | wg-usd-assets equivalent  | Notes                                                                         | Bring Over?|
|-------------                      | -------------             |  -------------                                                                |   ---------|  
| AlphaBlendModeTest                |AlphaBlendModeTest         |                                                                               |No          |
| AttenuationTest                   |None                       |                                                                               |Yes         |
| ClearCoatTest                     |None                       |Specific to KHR_materials_clearcoat                                            |No          |
| EnvironmentTest                   |None                       |                                                                               |Yes?        |
| LightsPunctualLamp                |None                       |Specific to KHR_lights_punctual                                                |No?         |
| MetalRoughSpheres                 |RoughnessTest?             |Not 1-1 but some similarities                                                  |Not Sure    |
| MetalRoughSpheresNoTextures       |RoughnessTest?             |Not 1-1 but some similarities                                                  |Not Sure    |
| MultiUVTest                       |NormalsTextureBiasAndScale?|Not 1-1 but some similarities                                                  |Not Sure    |
| NormalTangentMirrorTest           |NormalsTextureBiasAndScale |Seems similar enough to me                                                     |No          |
| NormalTangentTest                 |NormalsTextureBiasAndScale |Seems similar enough to me                                                     |No          |
| OrientationTest                   |TextureTransformTest?      |Not 1-1 but some similarities                                                  |Not Sure    |
| SpecularTest                      |None                       |Specific to KHR_materials_specular                                             |No          |
| TextureCoordinateTest             |None?                      |                                                                               |Yes         |
| TextureSettingsTest               |None?                      |                                                                               |Yes         |
| TransmissionRoughnessTest         |None?                      |Specific to KHR_materials_transmission, KHR_materials_ior, KHR_materials_volume|No          |
| TransmissionTest                  |TransmissionTest           |Specific to KHR_materials_transmission                                         |No          |
| VectorColorTest                   |PrimvarInterpolation       |                                                                               |No          |
| Accessor_Sparse                   |None?                      |                                                                               |Not Sure    |
| Accessor_SparseType               |None?                      |                                                                               |Not Sure    |
| Buffer_Interleaved                |PrimvarInterpolation?      |Not 1-1 but some similarities                                                  |Not Sure    |
| Instancing                        |None?                      |                                                                               |Yes         |
| Material                          |MaterialXTest?             |Not 1-1 but some similarities                                                  |Not Sure    |
| Material_AlphaBlend               |AlphaBlendModeTest?        |Not 1-1 but some similarities                                                  |Not Sure    |
| Material_AlphaMask                |None?                      |                                                                               |Yes         |
| Material_DoubleSided              |None?                      |                                                                               |Yes         |
| Material_MetallicRoughness        |RoughnessTest?             |Not 1-1 but some similarities                                                  |Not Sure    |
| Mesh_PrimitiveAttribute           |PrimvarInterpolation       |                                                                               |No          |
| Mesh_PrimitiveMode                |PrimvarInterpolation       |                                                                               |No          |
| Mesh_PrimitiveVertexColor         |PrimvarInterpolation       |                                                                               |No          |
| Mesh_Primitives                   |PrimvarInterpolation       |                                                                               |No          |
| Mesh_PrimitivesUV                 |NormalsTextureBiasAndScale |Not 1-1 but some similarities                                                  |Not Sure    |
| Node_Attribute                    |Schema/usdGeom/Transforms  |                                                                               |No          |
| Node_NegativeScale                |Schema/usdGeom/Transforms  |                                                                               |No          |
| Texture_Sampler                   |None?                      |                                                                               |Yes         |
| Geompropvis                       |PrimvarInterpolation?      |Not 1-1 but some similarities                                                  |Not Sure    |
| TextureEncodingTest               |None?                      |                                                                               |Yes?        |

**Comment by jcowles** [comment]
@beersandrew can this be closed now?

**Comment by beersandrew** [comment]
Yeah, this is more of a description of what I did rather than an issue anyway, we don’t have 100% parity with the glTF sample asset repo but I don’t think that was the goal.
