### ISSUE TITLE
Assets don't pass usdchecker: Missing MaterialBindingAPI

### ISSUE THREAD

**Issue by bjorn-siegert-adsk** [usd-wg/assets#55]
Running usdchecker on the test assets shows that the MaterialBindingAPI is not applied to prims which is necessary using Hydra v2.

e.g. https://github.com/usd-wg/assets/blob/main/test_assets/MaterialXTest/basicTextured.usda

```
usdchecker /Users/siegerb/Library/CloudStorage/OneDrive-Autodesk/MAYA_PROJECTS/library/assets/test_assets/MaterialXTest/basicTextured.usda         
Stage does not specify its linear scale in metersPerUnit. (fails 'StageMetadataChecker')
Stage has missing or invalid defaultPrim. (fails 'StageMetadataChecker')
Found material bindings but no MaterialBindingAPI applied on the prim </Teapot/teapot_MeshShape>. (fails 'MaterialBindingAPIAppliedChecker')
Found material bindings but no MaterialBindingAPI applied on the prim </Teapot/teapot_MeshShape>. (fails 'MaterialBindingAPIAppliedChecker')
Failed!
```

**Comment by beersandrew** [comment]
hey @bjorn-siegert-adsk, thanks for posting.

I'm not able to reproduce this issue and I do see fixes for these issues in that file:
-  the metersPerUnit specified [here](https://github.com/usd-wg/assets/blob/main/test_assets/MaterialXTest/basicTextured.usda#L4)
-  default prim is defined [here](https://github.com/usd-wg/assets/blob/main/test_assets/MaterialXTest/basicTextured.usda#L5C11-L5C11)
- and the materials binding api is applied [here](https://github.com/usd-wg/assets/blob/main/test_assets/MaterialXTest/basicTextured.usda#L28) and [here](https://github.com/usd-wg/assets/blob/main/test_assets/MaterialXTest/basicTextured.usda#L37) 

these changes were recently made, maybe fetching will fix everything for you

**Comment by bjorn-siegert-adsk** [comment]
Oh, my bad. I though I pulled recently but apparently not. Yes, you are right the issues are fixed already. Sorry about that.
